[package]
name = "renderer"
version = "0.1.0"
authors = ["Ivan Komarov <Ivan.Komarov@dfyz.info>"]

[dependencies]
capnp = "*"
error-chain = "*"
memmap = "*"
num_cpus = "*"
owning_ref = "*"
png = "*"
xml-rs = "*"

# So that we have line numbers in backtraces with RUST_BACKTRACE=1.
[profile.release]
debug = true
