[package]
name = "renderer"
version = "0.1.0"
authors = ["Ivan Komarov <Ivan.Komarov@dfyz.info>"]
build = "build.rs"

[build-dependencies]
capnpc = "*"

[dependencies]
clap = "*"
googleprojection = "*"
log = "*"
slog-stdlog = "*"