[package]
name = "renderer"
version = "0.1.0"
authors = ["Ivan Komarov <Ivan.Komarov@dfyz.info>"]
build = "build.rs"

[build-dependencies]
capnpc = "*"

[dependencies]
capnp = "*"
clap = "*"
error-chain = "*"
hyper = "0.10"
log = "*"
memmap = "*"
owning_ref = "*"
slog-stdlog = "*"
xml-rs = "*"

[dev-dependencies]
rustc-serialize = "*"

[profile.release]
debug = true