[package]
name = "renderer"
version = "0.1.0"
authors = ["Ivan Komarov <Ivan.Komarov@dfyz.info>"]
build = "build.rs"

[build-dependencies]
capnpc = "*"

[dependencies]
capnp = "*"
clap = "*"
env_logger = "*"
error-chain = "*"
futures = "*"
hyper = "*"
libc = "*"
log = "*"
memmap = "*"
owning_ref = "*"
png = "*"
xml-rs = "*"

[dependencies.cairo-sys-rs]
version = "*"
features = ["v1_14", "png"]

[dev-dependencies]
rustc-serialize = "*"

[profile.release]
debug = true