[package]
name = "renderer"
version = "0.1.0"
authors = ["Ivan Komarov <Ivan.Komarov@dfyz.info>"]

[build-dependencies]
capnpc = "*"

[dependencies]
capnp = "*"
clap = "*"
env_logger = "*"
error-chain = "*"
futures = "*"
hyper = "*"
log = "*"
memmap = "*"
owning_ref = "*"
png = "*"
xml-rs = "*"

# So that we have line numbers in backtraces with RUST_BACKTRACE=1.
[profile.release]
debug = true