[package]
name = "renderer"
version = "0.1.0"
authors = ["Ivan Komarov <Ivan.Komarov@dfyz.info>"]
edition = "2018"

[dependencies]
byteorder = "*"
failure = "*"
memmap = "*"
num_cpus = "*"
owning_ref = "*"
png = "*"
rust-ini = "*"
stb_truetype = "*"
xml-rs = "*"
indexmap = { version = "*", optional = true }

[features]
perf-stats = ["indexmap"]

# So that we have line numbers in backtraces with RUST_BACKTRACE=1.
[profile.release]
debug = true
